version: "3.8"
services:
  bitly-database:
    container_name: bitly-database
    build:
      dockerfile: Dockerfile
      context: ./database
    image: yooyoun/bitly-database
    environment:
      - MYSQL_DATABASE=url_shortener
      - MYSQL_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - ./database/config:/etc/mysql/conf.d
    ports:
      - "3308:3306"
  bitly-backend-app:
    container_name: bitly-backend-app
    build: .
    depends_on:
      - bitly-database
    image: yooyoun/bitly-backend-app
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "80:8080"
    restart: always
